scalar DateTime

directive @upper on FIELD_DEFINITION

enum BookCategory {
  NOVELS
  COMIC
  COOK
  ESSAY
  TRAVEL_GUIDES
}

type Book {
  id: ID!
  title: String!
  author: Author!
  categories: [BookCategory!]!
  releaseDate: DateTime!
}

type Author {
  id: ID!
  name: String!
}

union SearchResult = Book | Author

input AddBook {
  title: String!
  authorId: ID!
  categories: [BookCategory!]
  releaseDate: DateTime!
}

type Query {
  books: [Book!]!
  authors: [Author!]!
  search(q: String): [SearchResult!]!
  hello: String! @upper
}

type Mutation {
  addBook(book: AddBook!): Book!
}
